#!/bin/bash

# Pide al usuario el nombre del subdominio
read -p "Introduce el nombre del subdominio: " subdominio

# Define la dirección IP del servidor que se asociará con el subdominio
IP="192.168.237.131"

# Extrae el nombre del subdominio sin el dominio principal
nombreSubdominio=$(echo $subdominio | cut -d"." -f1)

# Obtiene la dirección IP de la máquina local
LOCAL_IP=$(hostname -I | awk '{print $1}')

# Crea el directorio de zonas si no existe
if [ ! -d "/etc/bind/zones" ]; then
    sudo mkdir -p /etc/bind/zones
    sudo chown bind:bind /etc/bind/zones
fi

# Crea el registro de zona directa
echo "Creating forward lookup zone for $subdominio"
echo "
\$ORIGIN $subdominio.
\$TTL 86400
@ IN SOA ns1.$subdominio. admin.$subdominio. (
   2023022601 ; serial
   3600       ; refresh (1 hour)
   1800       ; retry (30 minutes)
   604800     ; expire (1 week)
   86400      ; minimum (1 day)
   )
@ IN NS ns1.$subdominio.
ns1 IN A $LOCAL_IP
$nombreSubdominio IN A $IP" > /etc/bind/zones/$subdominio.zone

# Crea el registro de zona inversa
echo "Creating reverse lookup zone for $IP"
IP_REVERSED=$(echo $IP | awk -F. '{print $3"."$2"."$1}')
echo "
\$ORIGIN $IP_REVERSED.in-addr.arpa.
\$TTL 86400
@ IN SOA ns1.$subdominio. admin.$subdominio. (
   2023022601 ; serial
   3600       ; refresh (1 hour)
   1800       ; retry (30 minutes)
   604800     ; expire (1 week)
   86400      ; minimum (1 day)
   )
@ IN NS ns1.$subdominio.
$IP_REVERSED IN PTR $subdominio." > /etc/bind/zones/$IP_REVERSED.in-addr.arpa.zone

# Agrega las nuevas zonas al archivo de configuración del servidor DNS
echo "Adding new zones to named.conf.local"
echo "
zone \"$subdominio\" {
    type master;
    file \"/etc/bind/zones/$subdominio.zone\";
};

zone \"$IP_REVERSED.in-addr.arpa\" {
    type master;
    file \"/etc/bind/zones/$IP_REVERSED.in-addr.arpa.zone\";
};" >> /etc/bind/named.conf.local

# Reinicia el servicio de DNS
echo "Restarting named service"
service bind9 restart

echo "subdominio created successfully"
