#!/bin/bash

# Instalar los paquetes necesarios
sudo apt-get update
sudo apt-get install python3 python3-pip python3-dev libpq-dev nginx

# Crear un entorno virtual
sudo -H pip3 install virtualenv
mkdir ~/myproject
cd ~/myproject
virtualenv myprojectenv
source myprojectenv/bin/activate

# Instalar dependencias de la aplicación
pip install django gunicorn psycopg2-binary

# Configurar Django
django-admin.py startproject myproject ~/myproject
cd ~/myproject
python manage.py migrate

# Configurar Gunicorn
gunicorn_config='/etc/systemd/system/gunicorn.service'
sudo touch $gunicorn_config
echo "[Unit]" | sudo tee -a $gunicorn_config
echo "Description=gunicorn daemon" | sudo tee -a $gunicorn_config
echo "After=network.target" | sudo tee -a $gunicorn_config

echo "" | sudo tee -a $gunicorn_config

echo "[Service]" | sudo tee -a $gunicorn_config
echo "User=$USER" | sudo tee -a $gunicorn_config
echo "Group=www-data" | sudo tee -a $gunicorn_config
echo "WorkingDirectory=/home/$USER/myproject" | sudo tee -a $gunicorn_config
echo "ExecStart=/home/$USER/myproject/myprojectenv/bin/gunicorn \ " | sudo tee -a $gunicorn_config
echo "--workers 3 \ " | sudo tee -a $gunicorn_config
echo "--bind unix:/home/$USER/myproject/myproject.sock \ " | sudo tee -a $gunicorn_config
echo "myproject.wsgi:application" | sudo tee -a $gunicorn_config

echo "" | sudo tee -a $gunicorn_config

echo "[Install]" | sudo tee -a $gunicorn_config
echo "WantedBy=multi-user.target" | sudo tee -a $gunicorn_config

# Configurar Nginx
nginx_config='/etc/nginx/sites-available/myproject'
sudo touch $nginx_config
echo "server {" | sudo tee -a $nginx_config
echo "    listen 80;" | sudo tee -a $nginx_config
echo "    server_name server_domain_or_IP;" | sudo tee -a $nginx_config
echo "" | sudo tee -a $nginx_config
echo "    location / {" | sudo tee -a $nginx_config
echo "        include proxy_params;" | sudo tee -a $nginx_config
echo "        proxy_pass http://unix:/home/$USER/myproject/myproject.sock;" | sudo tee -a $nginx_config
echo "    }" | sudo tee -a $nginx_config
echo "}" | sudo tee -a $nginx_config

sudo ln -s /etc/nginx/sites-available/myproject /etc/nginx/sites-enabled

# Reiniciar los servicios
sudo systemctl daemon-reload
sudo systemctl start gunicorn
sudo systemctl enable gunicorn
sudo systemctl restart nginx